# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtWidgets
import cv2  # cv2是python中计算机视觉库OpenCV的一个模块，全称是Open Source Computer Vision Library（开放源代码计算机视觉库）
from PyQt5 import QtCore, QtGui, QtWidgets
import mediapipe as mp
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import time
import sys
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import QTimer
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
pose = mp_pose.Pose()

######################################################################################3

def get_pose(img):
    h, w = img.shape[0], img.shape[1]
    img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(img_RGB)
    if results.pose_landmarks:
        coordinate = []
        for i in range(33):
            cx = int(results.pose_landmarks.landmark[i].x * w)
            cy = int(results.pose_landmarks.landmark[i].y * h)
            single = [i, cx, cy]
            coordinate.append(single)
        return coordinate
    return None

def process_frame(img):
    h, w = img.shape[0], img.shape[1]
    img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(img_RGB)
    if results.pose_landmarks:
        mp_drawing.draw_landmarks(img, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
    else:
        cv2.putText(img, 'No Person', (25, 75), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (255, 0, 255), 2)
        print('No person detected in the image.')

    return img

def calculate_distance(p1, p2):
    return np.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)

def calculate_angle(p1, p2, p3):
    a = np.array([p1[0], p1[1]])
    b = np.array([p2[0], p2[1]])
    c = np.array([p3[0], p3[1]])

    radians = np.arctan2(c[1] - b[1], c[0] - b[0]) - np.arctan2(a[1] - b[1], a[0] - b[0])
    angle = np.abs(radians * 180.0 / np.pi)

    if angle > 180.0:
        angle = 360 - angle

    return angle
def check_posture(landmarks, img):
    try:
        img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        draw = ImageDraw.Draw(img_pil)
        font_path = "msyh.ttc"
        font = ImageFont.truetype(font_path, 20)

        # 关键点索引
        LEFT_SHOULDER = mp_pose.PoseLandmark.LEFT_SHOULDER.value
        RIGHT_SHOULDER = mp_pose.PoseLandmark.RIGHT_SHOULDER.value
        LEFT_WRIST = mp_pose.PoseLandmark.LEFT_WRIST.value
        RIGHT_WRIST = mp_pose.PoseLandmark.RIGHT_WRIST.value
        NOSE = mp_pose.PoseLandmark.NOSE.value

        # 手间距检测
        left_wrist = np.array([landmarks[LEFT_WRIST][1], landmarks[LEFT_WRIST][2]])
        right_wrist = np.array([landmarks[RIGHT_WRIST][1], landmarks[RIGHT_WRIST][2]])
        wrist_distance = np.linalg.norm(left_wrist - right_wrist)

        left_shoulder = np.array([landmarks[LEFT_SHOULDER][1], landmarks[LEFT_SHOULDER][2]])
        right_shoulder = np.array([landmarks[RIGHT_SHOULDER][1], landmarks[RIGHT_SHOULDER][2]])
        shoulder_distance = np.linalg.norm(left_shoulder - right_shoulder)

        # 头部位置检测
        nose_y = landmarks[NOSE][2]
        left_wrist_y = landmarks[LEFT_WRIST][2]
        right_wrist_y = landmarks[RIGHT_WRIST][2]

        messages = []
        messages2=[]
        messages3=[]
        draw.text((25, 20), "请侧向站立", font=font, fill=(0, 0, 0))

        if wrist_distance < shoulder_distance :
            messages.append("动作不正确：手间距应略大于肩膀")
            draw.text((25, 50), "动作不正确：手间距应略大于肩膀", font=font, fill=(0, 0, 0))

        if nose_y > left_wrist_y and nose_y > right_wrist_y:
            messages2.append("动作不正确：头部位置低于双手")
            draw.text((25, 80), "动作不正确：头部位置低于双手", font=font, fill=(0, 0, 0))

        if (wrist_distance > shoulder_distance )and(nose_y < left_wrist_y and nose_y < right_wrist_y):
            messages3.append("动作正确")
            draw.text((25, 170), "动作正确", font=font, fill=(0, 0, 0))

        img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)

    except Exception as e:
        print(f"Error in check_posture function: {str(e)}")

    return img, messages,messages2,messages3
########################################################################################################
class Ui_QMainWindow(QtWidgets.QMainWindow):
    def __init__(self):  # 构造方法
        super(Ui_QMainWindow, self).__init__()
        self.setupUi(self)
        ########################################################
        # 在类构造函数中初始化一些额外的东西
        self.camera_timer = QTimer()  # 创建定时器QTimer对象（camera_timer）
        self.cap = cv2.VideoCapture(0)  # 初始化cv2.VideoCapture对象
        self.init()  # 构建init方法

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 881, 591))
        self.listView.setStyleSheet("background-image: url(:/pic27.png)")
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 320, 61, 51))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 Heavy")
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 410, 61, 51))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 Heavy")
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 441, 241))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 451, 41))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 400, 461, 41))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 470, 461, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开始锻炼"))
        self.pushButton_2.setText(_translate("MainWindow", "停止锻炼"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))

    def init(self):
        self.pushButton.clicked.connect(self.open_camera)  # 绑定打开相机槽函数open_camera
        self.pushButton_2.clicked.connect(self.close_camera)  # 绑定关闭相机槽函数close_camera
        self.camera_timer.timeout.connect(self.show_image)  # 绑定显示图片槽函数show_image

    ########################################################
    # 以下是自定义的槽函数及其他衍生的自定义功能函数
    def open_camera(self):  # 打开相机
        self.cap = cv2.VideoCapture(0)  # 摄像头
        self.camera_timer.start(40)  # 每40毫秒读取一次，即刷新率为25帧

    # 修改 show_image 函数来显示检测到的文字信息
    def show_image(self):  # 显示图片
        flag, self.image = self.cap.read()  # 从视频流中读取图片
        if not flag:
            return

        self.image = process_frame(self.image)  # 处理每一帧视频图像
        coordinate = get_pose(self.image)  # 获取姿势坐标
        messages = []
        messages2 = []
        messages3 = []
        if coordinate:
            self.image, messages,messages2,messages3 = check_posture(coordinate, img=self.image)  # 检查姿势并标注

        image_show = cv2.cvtColor(self.image, cv2.COLOR_BGR2RGB)  # 转为 RGB 格式

        height, width, channel = image_show.shape
        step = channel * width
        qImg = QImage(image_show.data, width, height, step, QImage.Format_RGB888)

        pixmap = QPixmap.fromImage(qImg)
        scaled_pixmap = pixmap.scaled(self.label.size(), QtCore.Qt.KeepAspectRatio)

        self.label.setPixmap(scaled_pixmap)

        # 在 label_2 中显示检测到的文字信息
        self.label_2.setText("\n".join(messages))
        self.label_3.setText("\n".join(messages2))
        self.label_4.setText("\n".join(messages3))
    def close_camera(self):  # 关闭摄像头
        self.camera_timer.stop()  # 停止读取
        self.cap.release()  # 释放摄像头
        self.label_3.clear()  # 清除label_3组件上的图片
        self.label_3.setText("TextLabel")  # 设置文字在界面上


import text8_rc

# 主函数

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    main_win = Ui_QMainWindow()
    main_win.show()
    sys.exit(app.exec_())